[workspace]

members = ["mlx-rust", "mlx-ffi-trampoline", "mlx-sys", "examples/*"]
resolver = "2"


[workspace.dependencies]
mlx-rust = { path = "mlx-rust" }
mlx-ffi-trampoline = { path = "mlx-ffi-trampoline" }
mlx-sys = { path = "mlx-sys" }
paste = "1.0"
