[package]
name = "mlx-rust"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
half = "2.4"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]

bindgen = "0.65.1"
cmake = "0.1"
