[package]
name = "mlx-nn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mlx-rust = {workspace = true}
mlx-derive = {workspace = true}
serde = {workspace = true}
half = {workspace = true}