[package]
name = "basic_examples"
version = "0.1.0"
edition = "2021"

[dependencies]
mlx-rust = { workspace = true }
mlx-sys = { workspace = true}
mlx-nn = {workspace = true}
half = {workspace = true}